export const STARTER_CONTENT = {
 weapon:[
  {name:"Daga",system:{skill:"lightWeapons",attackAttribute:"agi",damage:3,damageType:"piercing",damageMode:"lethal",penetration:0,strengthMin:0,priceCopper:60,priceQuantity:1,priceStatus:"exact",legacyPrice:5,properties:"Ligera, Ocultable"}},
  {name:"Espada corta",system:{skill:"lightWeapons",attackAttribute:"agi",damageAttribute:"fue",damage:4,damageType:"slashing",damageMode:"lethal",penetration:0,strengthMin:0,priceCopper:100,priceQuantity:1,priceStatus:"exact",legacyPrice:12,properties:"Ligera"}},
  {name:"Sable",system:{skill:"lightWeapons",attackAttribute:"agi",damageAttribute:"fue",damage:4,damageType:"slashing",damageMode:"lethal",penetration:0,strengthMin:0,priceCopper:150,priceQuantity:1,priceStatus:"exact",legacyPrice:18,properties:"Ágil"}},
  {name:"Espada larga",system:{skill:"martialWeapons",attackAttribute:"fue",damageAttribute:"fue",damage:5,damageType:"slashing",damageMode:"lethal",penetration:0,strengthMin:1,priceCopper:200,priceQuantity:1,priceStatus:"exact",legacyPrice:20,properties:"Versátil"}},
  {name:"Hacha",system:{skill:"martialWeapons",attackAttribute:"fue",damageAttribute:"fue",damage:6,damageType:"slashing",damageMode:"lethal",penetration:0,strengthMin:2,priceCopper:250,priceQuantity:1,priceStatus:"exact",legacyPrice:18,properties:"Impactante"}},
  {name:"Maza",system:{skill:"martialWeapons",attackAttribute:"fue",damageAttribute:"fue",damage:5,damageType:"bludgeoning",damageMode:"lethal",penetration:1,strengthMin:1,priceCopper:100,priceQuantity:1,priceStatus:"exact",legacyPrice:16,properties:"Impactante"}},
  {name:"Martillo de guerra",system:{skill:"martialWeapons",attackAttribute:"fue",damageAttribute:"fue",damage:6,damageType:"bludgeoning",damageMode:"lethal",penetration:2,strengthMin:2,priceCopper:300,priceQuantity:1,priceStatus:"exact",legacyPrice:24,properties:"Impactante"}},
  {name:"Lanza",system:{skill:"martialWeapons",attackAttribute:"fue",damageAttribute:"fue",damage:5,damageType:"piercing",damageMode:"lethal",penetration:0,strengthMin:1,priceCopper:50,priceQuantity:1,priceStatus:"exact",legacyPrice:12,properties:"Alcance, 2 manos"}},
  {name:"Alabarda",system:{skill:"heavyWeapons",attackAttribute:"fue",damageAttribute:"fue",damage:7,damageType:"slashing",damageMode:"lethal",penetration:1,strengthMin:2,priceCopper:300,priceQuantity:1,priceStatus:"exact",legacyPrice:30,properties:"Alcance, Pesada, 2 manos"}},
  {name:"Mandoble",system:{skill:"heavyWeapons",attackAttribute:"fue",damageAttribute:"fue",damage:7,damageType:"slashing",damageMode:"lethal",penetration:0,strengthMin:2,priceCopper:400,priceQuantity:1,priceStatus:"exact",legacyPrice:32,properties:"Pesada, 2 manos"}},
  {name:"Gran hacha",system:{skill:"heavyWeapons",attackAttribute:"fue",damageAttribute:"fue",damage:8,damageType:"slashing",damageMode:"lethal",penetration:0,strengthMin:3,priceCopper:500,priceQuantity:1,priceStatus:"exact",legacyPrice:34,properties:"Pesada, 2 manos"}},
  {name:"Gran martillo",system:{skill:"heavyWeapons",attackAttribute:"fue",damageAttribute:"fue",damage:7,damageType:"bludgeoning",damageMode:"lethal",penetration:2,strengthMin:3,priceCopper:500,priceQuantity:1,priceStatus:"exact",legacyPrice:40,properties:"Pesada, 2 manos"}},
  {name:"Arco corto",system:{skill:"rangedWeapons",attackAttribute:"agi",damageAttribute:"fue",damage:4,damageType:"piercing",damageMode:"lethal",penetration:0,power:2,rangeOptimal:15,priceCopper:100,priceQuantity:1,priceStatus:"exact",legacyPrice:15,properties:"Potencia 2"}},
  {name:"Arco largo",system:{skill:"rangedWeapons",attackAttribute:"agi",damageAttribute:"fue",damage:5,damageType:"piercing",damageMode:"lethal",penetration:1,power:3,rangeOptimal:30,priceCopper:200,priceQuantity:1,priceStatus:"exact",legacyPrice:25,properties:"Potencia 3, 2 manos"}},
  {name:"Ballesta",system:{skill:"rangedWeapons",attackAttribute:"per",damage:6,damageType:"piercing",damageMode:"lethal",penetration:1,reload:1,rangeOptimal:25,priceCopper:300,priceQuantity:1,priceStatus:"exact",legacyPrice:22,properties:"Recarga 1"}},
  {name:"Ballesta pesada",system:{skill:"rangedWeapons",attackAttribute:"per",damage:8,damageType:"piercing",damageMode:"lethal",penetration:2,reload:2,rangeOptimal:35,priceCopper:500,priceQuantity:1,priceStatus:"exact",legacyPrice:35,properties:"Recarga 2, 2 manos"}},
  {name:"Pistola temprana",system:{skill:"rangedWeapons",attackAttribute:"per",damage:6,damageType:"piercing",damageMode:"lethal",penetration:2,reload:2,rangeOptimal:15,priceCopper:1000,priceQuantity:1,priceStatus:"exact",legacyPrice:30,properties:"Recarga 2"}},
  {name:"Rifle temprano",system:{skill:"rangedWeapons",attackAttribute:"per",damage:7,damageType:"piercing",damageMode:"lethal",penetration:3,reload:2,rangeOptimal:40,priceCopper:1800,priceQuantity:1,priceStatus:"exact",legacyPrice:45,properties:"Recarga 2, 2 manos"}},
  {name:"Pistola repetidora",system:{availability:"rare",skill:"rangedWeapons",attackAttribute:"per",damage:6,damageType:"piercing",damageMode:"lethal",penetration:1,rangeOptimal:20,priceCopper:3500,priceQuantity:1,priceStatus:"exact",legacyPrice:50,properties:"Repetición"}},
  {name:"Rifle repetidor",system:{availability:"rare",skill:"rangedWeapons",attackAttribute:"per",damage:7,damageType:"piercing",damageMode:"lethal",penetration:2,rangeOptimal:35,priceCopper:4500,priceQuantity:1,priceStatus:"exact",legacyPrice:65,properties:"Repetición, 2 manos"}}
 ],
 armor:[
  {name:"Armadura ligera",system:{protection:1,strengthMin:0,priceCopper:150,priceQuantity:1,priceStatus:"exact",legacyPrice:12}},{name:"Armadura reforzada",system:{protection:2,strengthMin:0,priceCopper:400,priceQuantity:1,priceStatus:"exact",legacyPrice:25}},
  {name:"Malla",system:{protection:3,strengthMin:1,priceCopper:1000,priceQuantity:1,priceStatus:"exact",legacyPrice:40}},{name:"Armadura pesada",system:{protection:4,strengthMin:3,priceCopper:1600,priceQuantity:1,priceStatus:"exact",legacyPrice:60}},{name:"Placas",system:{protection:5,strengthMin:3,priceCopper:4000,priceQuantity:1,priceStatus:"exact",legacyPrice:85}}
 ],
 shield:[
  {name:"Broquel",system:{passiveDefense:1,block:0,strengthMin:0,priceCopper:50,priceQuantity:1,priceStatus:"exact",legacyPrice:10,properties:"Sin Bloqueo especial"}},
  {name:"Escudo estándar",system:{passiveDefense:1,block:2,strengthMin:0,priceCopper:150,priceQuantity:1,priceStatus:"exact",legacyPrice:18,frontalOnly:true,properties:"Bloqueo +2"}},
  {name:"Escudo pesado",system:{passiveDefense:2,block:2,strengthMin:2,movementPenalty:-1,priceCopper:300,priceQuantity:1,priceStatus:"exact",legacyPrice:30,frontalOnly:true,properties:"Bloqueo +2; Movimiento -1"}}
 ],
 spell:[
  // Evocación
  {name:"Luz Arcana",system:{discipline:"evocation",grade:"minor",manaCost:2,attribute:"int",range:"3 espacios",duration:"Escena",effect:"Crea luz arcana real en un punto u objeto; ilumina aproximadamente 4 espacios. No revela invisibilidad, no ciega y no detecta magia."}},
  {name:"Proyectil Ígneo",system:{discipline:"evocation",grade:"basic",manaCost:3,attribute:"int",defense:"normal",damage:6,damageType:"fire",damageMode:"lethal",penetration:2,range:"Medio",requiresTarget:true,targetMode:"single"}},
  {name:"Onda de Choque",system:{discipline:"evocation",grade:"basic",manaCost:4,attribute:"int",defense:"normal",damage:4,damageType:"kinetic",damageMode:"lethal",penetration:0,range:"Área corta",area:"Frontal corta",effect:"Afecta a cada criatura en el frente; aliados incluidos salvo discriminación expresa. Empuja 1 espacio cuando la geometría lo permite."}},
  {name:"Barrera Cinética",system:{discipline:"evocation",grade:"basic",manaCost:3,attribute:"int",activation:"Reacción",effect:"+2 Defensa normal contra el ataque declarado; se consume al resolverlo."}},
  {name:"Aguja Gélida",system:{discipline:"evocation",grade:"advanced",manaCost:5,attribute:"int",defense:"normal",damage:5,damageType:"cold",damageMode:"lethal",penetration:2,range:"Medio",requiresTarget:true,targetMode:"single",effect:"Si impacta, Movimiento -2 hasta el final del siguiente turno del objetivo, mínimo 1. No se acumula; repetir refresca la duración."}},
  {name:"Arco Fulminante",system:{discipline:"evocation",grade:"advanced",manaCost:6,attribute:"int",defense:"normal",damage:4,damageType:"lightning",damageMode:"lethal",penetration:1,range:"Medio",requiresTarget:true,targetMode:"multiple",maxTargets:3,effect:"Cadena selectiva de hasta 3 objetivos; cada objetivo posterior debe estar a 3 espacios o menos del anterior. Un mismo Actor sólo puede ser afectado una vez."}},
  {name:"Martillo Cinético",system:{discipline:"evocation",grade:"advanced",manaCost:5,attribute:"int",defense:"body",damage:3,damageType:"kinetic",damageMode:"lethal",penetration:0,range:"Medio",requiresTarget:true,targetMode:"single",effect:"Desplaza 2 espacios a una criatura de Escala igual o menor, 1 si es una categoría mayor y 0 si es dos o más categorías mayor o está anclada. El daño se aplica si la tirada tiene éxito aunque el desplazamiento sea imposible."}},
  {name:"Pantalla Cinética",system:{discipline:"evocation",grade:"master",manaCost:8,attribute:"int",sustained:true,duration:"Sostenida · máximo una Escena",range:"Corta",area:"Pantalla hasta 3 espacios",effect:"Crea cobertura cinética equivalente a +2 Defensa para ataques que atraviesan la pantalla. No se acumula con cobertura equivalente y no es una pared física."}},
  {name:"Rayo de Ruptura",system:{discipline:"evocation",grade:"master",manaCost:10,attribute:"int",defense:"normal",damage:8,damageType:"arcane",damageMode:"lethal",penetration:4,range:"8 espacios",area:"Línea de 8 espacios",effect:"Afecta a todas las criaturas en la línea, incluidos aliados. Sin discriminación automática."}},
  {name:"Tormenta Arcana",system:{discipline:"evocation",grade:"legendary",manaCost:12,attribute:"int",defense:"normal",damage:8,damageType:"arcane",damageMode:"lethal",penetration:2,range:"Medio",area:"Radio 3 espacios",effect:"Una sola resolución se compara con la Defensa de cada criatura del área; aliados incluidos. No deja una zona de daño persistente."}},

  // Alteración
  {name:"Respiración Adaptada",system:{discipline:"alteration",grade:"minor",manaCost:2,attribute:"int",sustained:true,duration:"Sostenida",effect:"Adapta la respiración a aire o agua compatible. No protege de toxinas, presión, temperatura ni otros peligros ambientales."}},
  {name:"Potencia Sobrenatural",system:{discipline:"alteration",grade:"basic",manaCost:4,attribute:"int",sustained:true,effect:"Interactúa como una categoría de Escala mayor; no aumenta FUE/daño/Defensa, tamaño ni alcance."}},
  {name:"Piel Alterada",system:{discipline:"alteration",grade:"basic",manaCost:4,attribute:"int",sustained:true,effect:"Protección 2 contra categoría coherente; no acumula con armadura equivalente."}},
  {name:"Adherencia",system:{discipline:"alteration",grade:"basic",manaCost:3,attribute:"int",sustained:true,duration:"Sostenida",effect:"Permite desplazarse por paredes y techos físicamente compatibles. No aumenta Movimiento; superficies móviles, frágiles o sobrenaturales pueden exigir prueba contextual."}},
  {name:"Morfología Flexible",system:{discipline:"alteration",grade:"basic",manaCost:4,attribute:"int",sustained:true,duration:"Sostenida",effect:"Permite deformarse para atravesar huecos estrechos y facilita escapar de restricciones compatibles. No cambia Escala, ocupación, alcance ni fuerza y no escapa automáticamente de una Presa."}},
  {name:"Miembro Efímero",system:{discipline:"alteration",grade:"advanced",manaCost:5,attribute:"int",sustained:true,duration:"Sostenida",effect:"Crea un miembro adicional capaz de sostener o manipular. No concede Acción, Reacción, ataque adicional ni beneficio mecánico extra de escudo."}},
  {name:"Cuerpo Mineral",system:{discipline:"alteration",grade:"advanced",manaCost:6,attribute:"int",sustained:true,duration:"Sostenida",effect:"Protección 3 contra daño físico ordinario y Movimiento -2. No se acumula con armadura equivalente ni con Piel Alterada equivalente."}},
  {name:"Fase Parcial",system:{discipline:"alteration",grade:"advanced",manaCost:7,attribute:"int",activation:"Acción",effect:"Durante el Movimiento asociado permite cruzar una barrera sólida de hasta 1 espacio de espesor. Debe terminar en un espacio válido y libre; no es teletransporte ni permite permanecer dentro de materia."}},
  {name:"Morfología Alada",system:{discipline:"alteration",grade:"master",manaCost:8,attribute:"int",sustained:true,duration:"Sostenida · máximo una Escena",effect:"Genera estructuras de vuelo y permite volar hasta el Movimiento normal. No duplica Movimiento, no concede maniobrabilidad perfecta ni inmunidad a caídas o peso."}},
  {name:"Transmutación Corpórea",system:{discipline:"alteration",grade:"legendary",manaCost:12,attribute:"int",sustained:true,duration:"Sostenida · máximo una Escena",effect:"Adopta una Morfología Legendaria registrada: Escala +/-1 como máximo y hasta 2 Adaptaciones Mayores predefinidas. No concede conocimientos, Habilidades, hechizos, Maná, Reacciones ni poderes no registrados."}},

  // Restauración
  {name:"Conservación Orgánica",system:{discipline:"restoration",grade:"minor",manaCost:2,attribute:"int",duration:"24 horas",effect:"Preserva tejido, órganos o un cuerpo frente a degradación natural durante 24 horas. No cura, no resucita y no mantiene indefinidamente con vida."}},
  {name:"Cierre Restaurador",system:{discipline:"restoration",grade:"basic",manaCost:3,attribute:"int",requirements:"",requiresTarget:true,targetMode:"single",effect:"Recupera 4 Vida y detiene Sangrado ordinario compatible; no reduce Trauma ni repara automáticamente Herida Grave."}},
  {name:"Transferencia Vital",system:{discipline:"restoration",grade:"basic",manaCost:4,attribute:"int",requiresTarget:true,targetMode:"single",effect:"El lanzador pierde hasta 3 Vida y el objetivo recupera exactamente esa cantidad. El lanzador no puede quedar por debajo de 1 Vida; Protección no reduce esta pérdida."}},
  {name:"Regeneración",system:{discipline:"restoration",grade:"advanced",method:"ritual",manaCost:6,attribute:"int",difficulty:16,requirements:"Medicina Entrenada",skillRequirements:[{skill:"medicine",minRank:2}],effect:"Repara una Herida Grave orgánica compatible."}},
  {name:"Círculo Restaurador",system:{discipline:"restoration",grade:"advanced",manaCost:6,attribute:"int",requiresTarget:true,targetMode:"multiple",maxTargets:3,effect:"Hasta 3 criaturas cercanas recuperan 2 Vida cada una. No detiene Sangrado ni repara Heridas Graves."}},
  {name:"Restauración Funcional",system:{discipline:"restoration",grade:"advanced",manaCost:7,attribute:"int",requiresTarget:true,targetMode:"single",sustained:true,duration:"Sostenida · máximo una Escena",effect:"Suspende una penalización mecánica compatible de una Herida Grave. No cura la Herida, no reduce Trauma, no regenera partes ausentes ni vuelve posible una función físicamente inexistente."}},
  {name:"Reconstrucción",system:{discipline:"restoration",grade:"master",manaCost:10,attribute:"int",difficulty:20,requirements:"Medicina",effect:"Reconstrucción extraordinaria de daño orgánico compatible; no resurrección."}},
  {name:"Matriz Vital",system:{discipline:"restoration",grade:"master",manaCost:9,attribute:"int",requiresTarget:true,targetMode:"single",sustained:true,duration:"Sostenida · máximo 3 rondas",effect:"El objetivo recupera 2 Vida al final de cada una de hasta 3 rondas. No pulsa al lanzarse, no gana pulsos al reaplicarse y termina si el objetivo llega a 0 Vida; no levanta desde 0."}},
  {name:"Renovación Integral",system:{discipline:"restoration",grade:"legendary",method:"ritual",manaCost:14,attribute:"int",difficulty:23,requiresTarget:true,targetMode:"single",requirements:"Medicina Experta",skillRequirements:[{skill:"medicine",minRank:3}],effect:"Ritual mayor: recupera 10 Vida y repara hasta 2 Heridas Graves orgánicas compatibles. No reduce Trauma y no resucita."}},

  // Percepción e Ilusión
  {name:"Imagen Menor",system:{discipline:"perception",grade:"minor",manaCost:2,attribute:"per",sustained:true,duration:"Sostenida · máximo una Escena",effect:"Crea una imagen simple o un sonido simple. No tiene sustancia, no conversa autónomamente, no imita perfectamente a una persona y no aporta información desconocida. DF de examen = 11 + Atributo de lanzamiento + Canalización."}},
  {name:"Visión Arcana",system:{discipline:"perception",grade:"minor",manaCost:2,attribute:"per",difficulty:10,duration:"Escena",requirements:""}},
  {name:"Sintonía Emocional",system:{discipline:"perception",grade:"minor",manaCost:2,attribute:"per",range:"Corta",effect:"Percibe la emoción dominante de una criatura o presencia cercana cuando sea perceptible. No lee pensamientos, no detecta mentiras y no revela automáticamente la causa."}},
  {name:"Velo Sensorial",system:{discipline:"perception",grade:"basic",manaCost:3,attribute:"per",sustained:true,duration:"Sostenida · máximo una Escena",effect:"Oculta o disfraza un detalle sensorial concreto: color, cicatriz, objeto pequeño, sonido o rasgo facial limitado. No concede invisibilidad completa. DF de examen = 11 + Atributo de lanzamiento + Canalización."}},
  {name:"Espejismo",system:{discipline:"perception",grade:"basic",manaCost:4,attribute:"per",sustained:true,duration:"Sostenida · máximo una Escena",area:"Área pequeña",effect:"Ilusión visual y auditiva controlada dentro de un volumen limitado. No posee inteligencia, sustancia ni información que el lanzador desconozca. DF de examen = 11 + Atributo de lanzamiento + Canalización."}},
  {name:"Vínculo de Rastreo",system:{discipline:"perception",grade:"basic",manaCost:4,attribute:"per",difficulty:14,effect:"Obtiene dirección o región aproximada mediante un vínculo válido; no produce coordenadas GPS."}},
  {name:"Revelación Sensorial",system:{discipline:"perception",grade:"advanced",manaCost:5,attribute:"per",duration:"Escena",effect:"Concede Ventaja al examinar ilusiones, ocultación mágica, invisibilidad y manipulación sensorial compatibles. No concede omnisciencia, visión a través de paredes ni reemplaza Investigación/Percepción mundana."}},
  {name:"Duplicado Ilusorio",system:{discipline:"perception",grade:"advanced",manaCost:6,attribute:"per",sustained:true,duration:"Sostenida · máximo una Escena",effect:"Crea tres duplicados cercanos. Concede +2 Defensa contra ataques dependientes de visión mientras quede al menos un duplicado; cada ataque que falle por ese +2 destruye uno. No ocupan casillas, atacan, bloquean, flanquean ni generan una segunda tirada tras el impacto."}},
  {name:"Visión Remota",system:{discipline:"perception",grade:"advanced",manaCost:7,attribute:"per",difficulty:18,requirements:"Lugar conocido o ancla"}},
  {name:"Invisibilidad",system:{discipline:"perception",grade:"master",manaCost:9,attribute:"per",requiresTarget:true,targetMode:"single",sustained:true,duration:"Sostenida · máximo una Escena",effect:"El objetivo queda visualmente imperceptible. Sonido, huellas, agua, humo, polvo, olor y sentidos no visuales pueden delatarlo. Una acción ofensiva termina el efecto después de resolverse, acierte o falle, incluso mediante Origen Remoto. DF de examen = 11 + Atributo de lanzamiento + Canalización."}},
  {name:"Dominio Fantasmagórico",system:{discipline:"perception",grade:"legendary",manaCost:13,attribute:"per",sustained:true,duration:"Sostenida · máximo una Escena",area:"Área amplia",effect:"Ilusión multisensorial compleja de apariencia, sonido, luz percibida, movimiento aparente y sensación espacial superficial. No causa daño, fuerza, soporte ni obstáculos físicos. DF de examen = 11 + Atributo de lanzamiento + Canalización; una contradicción física directa puede revelar la falsedad pertinente."}},

  // Influencia
  {name:"Calma",system:{discipline:"influence",grade:"basic",manaCost:3,attribute:"pre",defense:"mental",requiresTarget:true,targetMode:"single",effect:"Reduce agitación emocional compatible sin borrar voluntad, memoria ni razones racionales para actuar."}},
  {name:"Valor Inspirado",system:{discipline:"influence",grade:"basic",manaCost:3,attribute:"pre",requiresTarget:true,targetMode:"single",sustained:true,duration:"Sostenida · máximo una Escena",effect:"+2 Defensa Mental únicamente contra miedo sobrenatural o intimidación compatible. No se acumula con Mente Anclada u otra protección mental mágica equivalente."}},
  {name:"Fascinación",system:{discipline:"influence",grade:"basic",manaCost:4,attribute:"pre",defense:"mental",requiresTarget:true,targetMode:"single",duration:"Hasta fin del siguiente turno del objetivo",effect:"El objetivo prioriza su atención hacia una persona, objeto o fenómeno especificado mientras no exista amenaza inmediata obvia. No queda inmovilizado ni pierde su Acción automáticamente."}},
  {name:"Temor",system:{discipline:"influence",grade:"basic",manaCost:4,attribute:"pre",defense:"mental",requiresTarget:true,targetMode:"single",duration:"Hasta fin del siguiente turno del objetivo",effect:"Una fuente presente se percibe como amenaza intensa. El objetivo conserva control de sus acciones; puede alejarse, cubrirse, defenderse o resistir según la ficción. No impone una secuencia obligatoria ni pérdida de Acción."}},
  {name:"Mente Anclada",system:{discipline:"influence",grade:"basic",manaCost:3,attribute:"pre",activation:"Reacción",effect:"+2 Defensa Mental contra el efecto mental declarado. No se acumula con Valor Inspirado u otra protección mental mágica equivalente."}},
  {name:"Concordia",system:{discipline:"influence",grade:"advanced",manaCost:5,attribute:"pre",defense:"mental",area:"Área social corta",duration:"Escena",effect:"Reduce hostilidad activa inmediata y abre disposición a escuchar. No crea amistad, perdón, acuerdo ni termina automáticamente un combate; razones racionales permanecen."}},
  {name:"Velo Social",system:{discipline:"influence",grade:"advanced",manaCost:5,attribute:"pre",sustained:true,duration:"Sostenida · máximo una Escena",effect:"El lanzador resulta mentalmente poco notable mientras actúe de forma ordinaria. Sigue físicamente visible; atacar, gritar, forzar accesos, robar abiertamente o entrar en una zona obviamente prohibida rompe la irrelevancia pertinente."}},
  {name:"Interdicción",system:{discipline:"influence",grade:"advanced",manaCost:6,attribute:"pre",requiresTarget:true,targetMode:"single",sustained:true,duration:"Sostenida · máximo una Escena",effect:"Protege a la criatura elegida. Cuando otra criatura intenta una acción hostil directa contra ella, resuelve PRE + Canalización del lanzador contra la Defensa Mental del atacante; con éxito, esa acción sufre Desventaja. No niega Acciones. Si el protegido daña al atacante, deja de proteger frente a él."}},
  {name:"Sugestión",system:{discipline:"influence",grade:"advanced",manaCost:5,attribute:"pre",defense:"mental",requiresTarget:true,targetMode:"single",effect:"Instrucción plausible y limitada; no Dominación, suicidio, pérdida repetida de Acción ni traición fundamental automática."}},
  {name:"Aura de Autoridad",system:{discipline:"influence",grade:"master",manaCost:9,attribute:"pre",sustained:true,duration:"Sostenida · máximo una Escena",area:"Radio 3 espacios",effect:"Cuando una criatura dentro del aura intenta una acción hostil directa contra el lanzador, resuelve PRE + Canalización del lanzador contra la Defensa Mental de esa criatura; con éxito, la acción sufre Desventaja. No niega Acciones. Si el lanzador la daña, el aura deja de protegerlo frente a ella durante la Escena."}},

  // Conjuración
  {name:"Objeto Efímero",system:{discipline:"conjuration",grade:"minor",manaCost:2,attribute:"int",sustained:true,duration:"Sostenida · máximo una Escena",effect:"Conjura un objeto simple, pequeño, inerte y manipulable con una mano. No crea dinero, munición, comida o medicina utilizable, explosivos, cristales de resonancia, mecanismos complejos ni herramientas que satisfagan por sí solas un requisito especializado. Relanzar reemplaza la instancia anterior."}},
  {name:"Llamada Menor",system:{discipline:"conjuration",grade:"basic",manaCost:4,attribute:"int",difficulty:14,sustained:true,duration:"Sostenida",effect:"Entidad menor compatible; no obediencia automática; ocupa Sostenimiento mientras permanezca presente."}},
  {name:"Paso Breve",system:{discipline:"conjuration",grade:"basic",manaCost:4,attribute:"int",difficulty:12,range:"3 espacios",remoteOriginCompatible:false,effect:"Teletransporta al lanzador hasta un destino visible, válido y desocupado a 3 espacios o menos."}},
  {name:"Trasposición",system:{discipline:"conjuration",grade:"advanced",manaCost:6,attribute:"int",difficulty:14,range:"8 espacios",requiresTarget:true,targetMode:"single",remoteOriginCompatible:false,effect:"Intercambia la posición del lanzador con una criatura voluntaria dentro de alcance. Ambas posiciones deben ser válidas; no concede Movimiento adicional ni permite un destino inválido o inmediatamente letal."}},
  {name:"Salto Vinculado",system:{discipline:"conjuration",grade:"advanced",manaCost:7,attribute:"int",range:"6 espacios",requiresTarget:true,targetMode:"multiple",maxTargets:2,remoteOriginCompatible:false,effect:"El lanzador y hasta 2 criaturas voluntarias a 1 espacio o menos se trasladan hasta 6 espacios. Todos los destinos deben ser visibles, libres, válidos y próximos entre sí."}},
  {name:"Umbral",system:{discipline:"conjuration",grade:"advanced",manaCost:7,attribute:"int",difficulty:18,remoteOriginCompatible:false,effect:"Abre un paso espacial local a través de una barrera continua de hasta 2 espacios de espesor. Una criatura voluntaria puede atravesarlo una vez antes de que se cierre. No conecta Anclas ni crea un Portal persistente."}},
  {name:"Jaula Dimensional",system:{discipline:"conjuration",grade:"master",manaCost:9,attribute:"int",sustained:true,duration:"Sostenida · máximo una Escena",area:"Radio 3 espacios",effect:"Todo efecto que intente teletransportar, abrir un Portal o invocar a través de la frontera usa una DF espacial mínima 18: DF efectiva = max(DF normal, 18). No añade una segunda resistencia, no bloquea movimiento ordinario ni proyectiles y afecta también a aliados."}},
  {name:"Llamada Mayor",system:{discipline:"conjuration",grade:"master",method:"ritual",manaCost:10,attribute:"int",difficulty:21,sustained:true,duration:"Sostenida",requirements:"Vínculo de invocación válido",effect:"Convoca una entidad significativa y predefinida mediante nombre, símbolo, pacto, reliquia u otra conexión válida. Invocar establece presencia, no obediencia; la entidad conserva voluntad y usa los modos Autónoma, Vinculada o Reactiva sin convertirse en un segundo PJ gratuito."}},
  {name:"Portal",system:{discipline:"conjuration",grade:"master",manaCost:10,attribute:"int",difficulty:21,requirements:"Anclas compatibles",remoteOriginCompatible:false,effect:"Abre una conexión transitable y temporal entre dos Anclas compatibles; normalmente requiere preparación prolongada."}},
  {name:"Gran Traslación",system:{discipline:"conjuration",grade:"legendary",method:"ritual",manaCost:14,attribute:"int",difficulty:24,targetMode:"multiple",maxTargets:8,requirements:"Dos Anclas compatibles",remoteOriginCompatible:false,effect:"Traslada instantáneamente al lanzador y hasta 8 criaturas voluntarias cercanas entre dos Anclas operativas compatibles. No admite objetivos hostiles, aparición dentro de materia, Anclas destruidas ni tránsito planar arbitrario."}}
 ],
 technique:[
  {name:"Parada",system:{grade:"basic",pdCost:2,activation:"Reacción",effect:"+2 Defensa contra ataque cuerpo a cuerpo parable."}},
  {name:"Golpe Potente",system:{grade:"basic",pdCost:2,effect:"-2 ataque; +2 daño."}},
  {name:"Recibir Carga",system:{grade:"basic",pdCost:2,activation:"Reacción",requirements:"Arma de Alcance",effect:"Cuando un enemigo entra voluntariamente en tu alcance mediante un desplazamiento directo hacia ti, realiza un ataque inmediato antes de que complete la aproximación. Daño normal; no detiene automáticamente el movimiento."}},
  {name:"Intercepción",system:{grade:"basic",pdCost:2,activation:"Reacción",effect:"Cuando un aliado cercano es objetivo de un ataque perceptible, desplázate lo mínimo por una trayectoria válida para interponerte y pasa a ser el objetivo. Sin Defensa adicional, sin teletransporte, sin exceder Movimiento y no contra áreas."}},
  {name:"Tirador Preparado",system:{grade:"basic",pdCost:2,activation:"Acción + Reacción",effect:"Disparo reactivo; expira al inicio del siguiente turno."}},
  {name:"Recarga Experta",system:{grade:"basic",pdCost:2,effect:"Reduce Recarga en 1 Acción respetando límites físicos."}},
  {name:"Combate Dual",system:{grade:"advanced",pdCost:3,effect:"Dos ataques -2 con armas Ligeras/compatibles; modificador de ataque completo solo en uno."}},
  {name:"Barrido",system:{grade:"advanced",pdCost:3,effect:"Una tirada -2 contra hasta dos objetivos válidos."}},
  {name:"Estocada Perforante",system:{grade:"advanced",pdCost:3,effect:"-1 ataque, -1 daño, Pen +2."}},
  {name:"Contraataque",system:{grade:"advanced",pdCost:3,requirements:"Parada",effect:"Ataque inmediato dentro de la misma Reacción tras Parada exitosa."}},
  {name:"Contramagia",system:{grade:"advanced",pdCost:3,activation:"Reacción",effect:"Interferencia compatible antes de resolver; no cancelación universal."}},
  {name:"Doble Sostenimiento",system:{grade:"master",pdCost:5,effect:"Mantiene dos efectos Sostenidos demandantes."}},
  {name:"Sentidos Compartidos",system:{grade:"basic",pdCost:2,requirements:"Familiar Mágico; Vínculo II",activation:"Acción",effect:"Percibe temporalmente mediante los sentidos reales del Familiar."}},
  {name:"Comunicación Mejorada",system:{grade:"basic",pdCost:2,requirements:"Familiar Mágico; Vínculo II",effect:"Permite conceptos complejos dentro del alcance válido del vínculo."}},
  {name:"Origen Remoto",system:{grade:"advanced",pdCost:3,requirements:"Familiar Mágico; Vínculo III",effect:"Permite usar la posición del Familiar como origen compatible; Maná, tirada y Sostenimiento siguen siendo del personaje."}},
  {name:"Coordinación Reactiva",system:{grade:"advanced",pdCost:3,requirements:"Familiar Mágico; Vínculo III",effect:"Define un disparador simple y observable para una respuesta; no genera Reacciones adicionales ni cadenas reactivas."}}
 ],
 formula:[
  {name:"Bálsamo Restaurador",system:{quantity:0,known:false,grade:"common",pdCost:1,preparation:"Base tópica estable",ingredients:"Reactivos restaurativos comunes",time:"2 h",dose:"1 aplicación",route:"Tópica",activation:"1 minuto",duration:"Instantánea",saturating:true,family:"restaurativa",effect:"Recupera 4 Vida; no Trauma/Herida Grave.",preservation:"Dosis sellada mientras envase/condiciones sigan intactos.",priceCopper:50,priceQuantity:1,priceStatus:"exact",legacyPrice:12}},
  {name:"Poción Restauradora",system:{quantity:0,known:false,grade:"common",pdCost:1,preparation:"Poción estable",ingredients:"Reactivos restaurativos comunes",time:"2 h",dose:"1 dosis",route:"Oral",activation:"Acción",duration:"Instantánea",saturating:true,family:"restaurativa",effect:"Acción: recupera 4 Vida, hasta el máximo y respetando límites de lesión; no reduce Trauma ni repara Heridas Graves.",preservation:"Dosis sellada mientras envase/condiciones sigan intactos.",priceCopper:80,priceQuantity:1,priceStatus:"exact",legacyPrice:12}},
  {name:"Poción de Recuperación Arcana",system:{quantity:0,known:false,grade:"refined",pdCost:1,preparation:"Poción estabilizada",ingredients:"Reactivos arcanos estabilizados",time:"4 h",dose:"1 dosis",route:"Oral",activation:"Acción",duration:"Instantánea",saturating:true,family:"arcana",effect:"Acción: recupera 3 Maná, hasta el máximo; no elimina Fatiga ni consecuencias de Sobrecarga.",preservation:"Dosis sellada mientras envase/condiciones sigan intactos.",priceCopper:150,priceQuantity:1,priceStatus:"exact",legacyPrice:15}},
  {name:"Tónico de Vigor",system:{quantity:0,known:false,grade:"refined",pdCost:1,preparation:"Tónico estable",ingredients:"Reactivos potenciadores",time:"4 h",dose:"1 dosis",route:"Oral",activation:"1 minuto",duration:"Hasta prueba compatible o fin de Escena",saturating:true,family:"potenciador",effect:"Ventaja en una prueba de VIG por esfuerzo prolongado.",preservation:"Dosis sellada mientras envase/condiciones sigan intactos.",priceCopper:80,priceQuantity:1,priceStatus:"exact",legacyPrice:10}},
  {name:"Supresor del Dolor",system:{quantity:0,known:false,grade:"refined",pdCost:1,preparation:"Preparación analgésica",ingredients:"Reactivos medicinales",time:"4 h",dose:"1 dosis",route:"Oral",activation:"Acción",duration:"Escena",saturating:true,family:"analgesica",effect:"Ignora una Desventaja causada por dolor compatible; no repara lesión.",preservation:"Dosis sellada mientras envase/condiciones sigan intactos.",priceCopper:80,priceQuantity:1,priceStatus:"exact",legacyPrice:15}},
  {name:"Neutralizante Común",system:{quantity:0,known:false,grade:"refined",pdCost:1,preparation:"Preparado para familia de toxina compatible",ingredients:"Reactivos antitóxicos",time:"4 h",dose:"1 dosis",route:"Definida al preparar la dosis",activation:"Acción cuando la vía preparada lo permite",duration:"Hasta siguiente resistencia compatible de la Escena",saturating:true,family:"antitoxica",effect:"Nueva resistencia con Ventaja contra toxina compatible.",preservation:"Dosis sellada mientras envase/condiciones sigan intactos.",priceCopper:100,priceQuantity:1,priceStatus:"exact",legacyPrice:10}},
  {name:"Toxina Debilitante",system:{quantity:0,known:false,grade:"complex",pdCost:2,preparation:"Toxina estable",ingredients:"Reactivos tóxicos ficticios",time:"1 Jornada",dose:"1 aplicación",route:"Sangre",activation:"Primera aplicación válida",latency:"Inmediata",resistance:"VIG DF14",duration:"Escena",saturating:false,family:"",effect:"VIG DF14; fallo: Desventaja en acciones físicas dependientes de fuerza muscular.",preservation:"Dosis sellada mientras envase/condiciones sigan intactos.",priceCopper:150,priceQuantity:1,priceStatus:"exact",legacyPrice:18}},
  {name:"Bomba Incendiaria",system:{quantity:0,known:false,grade:"complex",pdCost:2,preparation:"Carga incendiaria ficticia estabilizada",ingredients:"Reactivos incendiarios ficticios y carcasa compatible",time:"1 Jornada",dose:"1 bomba",route:"Colocación/lanzamiento",activation:"Colocación o lanzamiento",duration:"Instantánea",saturating:false,family:"",effect:"Área pequeña; Daño 6 Pen 1; resolución de colocación.",preservation:"Unidad sellada mientras carcasa/condiciones sigan intactas.",priceCopper:300,priceQuantity:1,priceStatus:"exact",legacyPrice:20}}
 ],
 ritual:[
  {name:"Círculo de Protección",system:{grade:"basic",pdCost:2,difficulty:15,time:"30 minutos",usefulAssistants:2,manaDirector:3,manaAssistantMax:1,effect:"Barrera contra categoría sobrenatural definida."}},
  {name:"Vínculo de Localización",system:{grade:"advanced",pdCost:3,difficulty:18,time:"2 horas",usefulAssistants:2,manaDirector:5,effect:"Dirección/región aproximada; no GPS."}},
  {name:"Portal Estable",system:{grade:"master",pdCost:5,difficulty:21,time:"8 horas",usefulAssistants:4,manaDirector:8,manaAssistantMax:2,flowRequired:3,effect:"Conexión temporal entre dos Anclas compatibles."}}
 ],
 device:[
  {name:"Celda arcana menor",system:{energy:{value:4,max:4},flow:2,chargingFlow:0,stability:1,consumption:0}},
  {name:"Acumulador estándar",system:{energy:{value:8,max:8},flow:3,chargingFlow:0,stability:2,consumption:0}},
  {name:"Núcleo pesado",system:{energy:{value:16,max:16},flow:5,chargingFlow:0,stability:4,consumption:0}},
  {name:"Escudo de campo",system:{flow:2,chargingFlow:0,stability:0,consumption:2,activation:"Reacción",kineticDefense:true,effect:"Reacción: +2 Defensa; no acumula con Barrera Cinética equivalente."}}
 ]
};
